"""add question_type_distribution to generation_jobs

Revision ID: 7e63872385e9
Revises: a3b78f5bbd0b
Create Date: 2026-09-26 07:52:57.782786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import backend.database.models


# revision identifiers, used by Alembic.
revision: str = '7e63872385e9'
down_revision: Union[str, Sequence[str], None] = 'a3b78f5bbd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (e.g. a real deployment with
    # jobs already created before this migration) with the same default
    # used at the Python model level, so NOT NULL never fails on existing data.
    op.add_column(
        'generation_jobs',
        sa.Column(
            'question_type_distribution',
            backend.database.models.JSONVariant(),
            nullable=False,
            server_default='{"single_best_answer": 1.0}',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_jobs', 'question_type_distribution')
    # ### end Alembic commands ###
