"""initial schema

Revision ID: a3b78f5bbd0b
Revises: 
Create Date: 2026-09-26 06:49:13.091634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import backend.database.models


# revision identifiers, used by Alembic.
revision: str = 'a3b78f5bbd0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('min_quality_score', sa.Double(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', backend.database.models.JSONVariant(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocked_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('generation_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('quantization', sa.String(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('vram_estimate_mb', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', 'quantization')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('academic_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('retrieval_date', sa.DateTime(), nullable=False),
    sa.Column('approved_domain_id', sa.Integer(), nullable=True),
    sa.Column('document_hash', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_domain_id'], ['approved_domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_hash')
    )
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_subject_id', sa.String(), nullable=False),
    sa.Column('subject_label_snapshot', sa.String(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('option_count', sa.Integer(), nullable=False),
    sa.Column('difficulty_distribution', backend.database.models.JSONVariant(), nullable=False),
    sa.Column('bloom_distribution', backend.database.models.JSONVariant(), nullable=False),
    sa.Column('source_policy', backend.database.models.JSONVariant(), nullable=False),
    sa.Column('internet_enabled', sa.Boolean(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PREPARING_KNOWLEDGE', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='generationjobstatus'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('over_generation_factor', sa.Double(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('option_count BETWEEN 3 AND 5', name='ck_option_count_range'),
    sa.CheckConstraint('requested_count > 0', name='ck_requested_count_positive'),
    sa.ForeignKeyConstraint(['model_id'], ['generation_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generation_jobs_status', 'generation_jobs', ['status'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_key', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_text', sa.String(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Double(), nullable=False),
    sa.Column('top_p', sa.Double(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('repeat_penalty', sa.Double(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['generation_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_key', 'version')
    )
    op.create_table('generation_job_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_job_id', sa.Integer(), nullable=False),
    sa.Column('external_topic_id', sa.String(), nullable=False),
    sa.Column('topic_label_snapshot', sa.String(), nullable=False),
    sa.Column('manual_context', sa.String(), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Double(), nullable=False),
    sa.CheckConstraint('target_count >= 0', name='ck_target_count_nonnegative'),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generation_job_topics_job', 'generation_job_topics', ['generation_job_id'], unique=False)
    op.create_table('generation_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_job_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Double(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_source_id', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_text_hash', sa.String(), nullable=True),
    sa.Column('ingestion_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['academic_source_id'], ['academic_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('external_subject_id', sa.String(), nullable=False),
    sa.Column('external_topic_id', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('embedding_vector_id', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_topic', 'document_chunks', ['external_subject_id', 'external_topic_id'], unique=False)
    op.create_table('mcq_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_job_id', sa.Integer(), nullable=False),
    sa.Column('generation_job_topic_id', sa.Integer(), nullable=False),
    sa.Column('prompt_template_id', sa.Integer(), nullable=False),
    sa.Column('generation_model_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('question_stem', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', name='bloomlevel'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('status', sa.Enum('GENERATED', 'STRUCTURE_VALIDATED', 'FACT_VALIDATED', 'DEDUPLICATED', 'QUALITY_CHECKED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'NEEDS_REVISION', 'DUPLICATE', 'INVALID', 'LOW_CONFIDENCE', name='mcqstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_job_topic_id'], ['generation_job_topics.id'], ),
    sa.ForeignKeyConstraint(['generation_model_id'], ['generation_models.id'], ),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mcq_candidates_job_status', 'mcq_candidates', ['generation_job_id', 'status'], unique=False)
    op.create_table('mcq_item_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcq_candidate_id', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('difficulty_index', sa.Double(), nullable=True),
    sa.Column('discrimination_index', sa.Double(), nullable=True),
    sa.Column('option_selection_distribution', backend.database.models.JSONVariant(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mcq_candidate_id'], ['mcq_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mcq_candidate_id')
    )
    op.create_table('mcq_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcq_candidate_id', sa.Integer(), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('latex_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mcq_candidate_id'], ['mcq_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mcq_candidate_id', 'option_index')
    )
    op.create_table('mcq_quality_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcq_candidate_id', sa.Integer(), nullable=False),
    sa.Column('factual_correctness', sa.Double(), nullable=True),
    sa.Column('source_grounding', sa.Double(), nullable=True),
    sa.Column('clarity', sa.Double(), nullable=True),
    sa.Column('distractor_quality', sa.Double(), nullable=True),
    sa.Column('single_correctness', sa.Double(), nullable=True),
    sa.Column('topic_relevance', sa.Double(), nullable=True),
    sa.Column('difficulty_match', sa.Double(), nullable=True),
    sa.Column('bloom_match', sa.Double(), nullable=True),
    sa.Column('option_conciseness', sa.Double(), nullable=True),
    sa.Column('notation_validity', sa.Double(), nullable=True),
    sa.Column('duplicate_risk', sa.Double(), nullable=True),
    sa.Column('composite_score', sa.Double(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mcq_candidate_id'], ['mcq_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mcq_candidate_id')
    )
    op.create_table('mcq_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcq_candidate_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action IN ('approve','reject','edit','regenerate','flag','change_difficulty','change_bloom')", name='ck_review_action_enum'),
    sa.ForeignKeyConstraint(['mcq_candidate_id'], ['mcq_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcq_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcq_candidate_id', sa.Integer(), nullable=False),
    sa.Column('document_chunk_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['mcq_candidate_id'], ['mcq_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcq_validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcq_candidate_id', sa.Integer(), nullable=False),
    sa.Column('validator_name', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('score', sa.Double(), nullable=True),
    sa.Column('details', backend.database.models.JSONVariant(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("result IN ('pass','fail','uncertain')", name='ck_validation_result_enum'),
    sa.ForeignKeyConstraint(['mcq_candidate_id'], ['mcq_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcq_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcq_candidate_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', backend.database.models.JSONVariant(), nullable=False),
    sa.Column('edited_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mcq_candidate_id'], ['mcq_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mcq_candidate_id', 'version_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcq_versions')
    op.drop_table('mcq_validation_results')
    op.drop_table('mcq_sources')
    op.drop_table('mcq_reviews')
    op.drop_table('mcq_quality_scores')
    op.drop_table('mcq_options')
    op.drop_table('mcq_item_stats')
    op.drop_index('ix_mcq_candidates_job_status', table_name='mcq_candidates')
    op.drop_table('mcq_candidates')
    op.drop_index('ix_document_chunks_topic', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('source_documents')
    op.drop_table('generation_metrics')
    op.drop_index('ix_generation_job_topics_job', table_name='generation_job_topics')
    op.drop_table('generation_job_topics')
    op.drop_table('prompt_templates')
    op.drop_index('ix_generation_jobs_status', table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_table('academic_sources')
    op.drop_table('users')
    op.drop_table('generation_models')
    op.drop_table('blocked_domains')
    op.drop_table('audit_log_entries')
    op.drop_table('approved_domains')
    # ### end Alembic commands ###
