"""Confirms the initial Alembic migration actually applies to a fresh
database and reverses cleanly -- an autogenerated migration that only
"looks right" but fails on `upgrade head` would defeat the point of
having migrations at all.
"""

from pathlib import Path

from alembic import command
from alembic.config import Config

BACKEND_DIR = Path(__file__).resolve().parents[1] / "backend"


def _alembic_config(db_url: str) -> Config:
    cfg = Config(str(BACKEND_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(BACKEND_DIR / "database" / "migrations"))
    cfg.set_main_option("sqlalchemy.url", db_url)
    return cfg


def test_migration_upgrades_and_downgrades_cleanly(tmp_path):
    db_path = tmp_path / "migration_test.db"
    cfg = _alembic_config(f"sqlite:///{db_path}")

    command.upgrade(cfg, "head")

    import sqlalchemy as sa

    engine = sa.create_engine(f"sqlite:///{db_path}")
    inspector = sa.inspect(engine)
    tables = set(inspector.get_table_names())
    for expected in ("generation_jobs", "mcq_candidates", "mcq_options", "users", "audit_log_entries"):
        assert expected in tables

    command.downgrade(cfg, "base")
    inspector = sa.inspect(engine)
    assert "generation_jobs" not in set(inspector.get_table_names())
